### ISSUE TITLE
You could use static length arrays here: https://stackoverflow.com/questions/25805174/creating-a-fixed-size-array-on-heap-in-rust

### ISSUE THREAD

**Issue by joppekoers** [jesseVDwolf/RustRaytracer#2]
https://github.com/jesseVDwolf/RustRaytracer/blob/350d480682a06f31e84a7710a861a7962dfa0521/src/sphere.rs#L21

**Comment by jesseVDwolf** [comment]
This better:
https://github.com/jesseVDwolf/RustRaytracer/blob/a03ccf76ccc655b3043ea214bf03c97b93699e7d/src/sphere.rs#L21
